# 5. 에러 핸들링1

# 📌 Resolve, Reject

```jsx
const delayAdd = index => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (index > 10) {
        reject(`${index}는 10보다 클 수 없습니다.`)
        return;
      }
      console.log(index);
      resolve(index + 1);
    }, 1000)
  })
}

delayAdd(13).then(res => console.log(res)).catch(err => console.error(err));

const wrap = async () => {
	const res = await delayAdd(2);
	console.log(res);
```

<aside>
💡 **Promise 생성자 → `resolve` , `reject` 두 파라미터 사용 가능, 서로 상충되는 개념**

`**resolve` 파라미터 호출 = `reject` 실행이 되지 않음**

`**reject` 파라미터 호출 = `resolve` 실행이 되지 않음**

</aside>

## Async, Await ❌

`then` 메소드 실행 → `resolve`

`catch` 메소드 실행 → `reject`

## Async, Await ✅

`await` 키워드로 해당 패턴 기억(대기)

하나의 변수로 생성 및 `console.log()` 로 받음